version: 0.0
os: linux
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands: 
#      - docker pull 374898892977.dkr.ecr.us-east-1.amazonaws.com/isr-table-generation:dev
#      - docker run -it --rm dev sh
hooks:
  AfterInstall:
    - location: scripts/install_docker.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_docker.sh
      timeout: 300
      runas: root	  
