version: 0.2
phases:
  pre_build:
    commands:
      - aws --version
      - echo $AWS_DEFAULT_REGION
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 374898892977.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=374898892977.dkr.ecr.us-east-1.amazonaws.com/isr-table-generation
   build:
     commands:
       - docker pull $REPOSITORY_URI:$IMAGE_TAG
       - sudo apt-get update
       - sudo apt install python3-pip
       - sudo pip3 install awsebcli --upgrade
