version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  build:
    commands:
      - curl -LJ0 https://github.com/nayakashutosh09/awssetup/variables.txt
      - echo $(pwd)
      - |
        while IFS= read -r line || [ -n "$line" ]; do
          export "$line"
        done < $(pwd)/variables.txt
      - echo "REGION is" $REGION
      - |
      - if [ "$REGION" = "ZAF" ]; then
          echo "A.....";
          echo "Logging in to Amazon ECR...";
          echo "$AWS_DEFAULT_REGION";
          echo "$(aws --version)";
          echo "$(REPOSITORY_URI1=374898892977.dkr.ecr.us-east-1.amazonaws.com/vsr-h2o-model)";
          echo "$(REPOSITORY_URI2=374898892977.dkr.ecr.us-east-1.amazonaws.com/vsr-pipeline)";
          echo "$(aws sts get-caller-identity)";
          echo "Logging in to Amazon ECR...";
          echo "$(curl -LJ0 https://github.com/nayakashutosh09/awssetup/pipeline-config.json)";
          echo "$(aws s3 cp pipeline-config.json s3://ci-cd-pipeline-precision-ag/Model_Management/ZAF/)";
          echo "$(pwd)";

          echo "$(aws s3 cp s3://ci-cd-pipeline-precision-ag/Model_Management/ZAF/calibrateddata.csv $(pwd)/vsr/tmp)";
          echo "$(aws s3 cp s3://ci-cd-pipeline-precision-ag/Model_Management/ZAF/regionaldata.json $(pwd)/vsr/tmp)";
          echo "$(aws s3 cp s3://ci-cd-pipeline-precision-ag/Model_Management/ZAF/runh2o.sh $(pwd)/vsr/tmp)";
          echo "$(aws s3 cp s3://ci-cd-pipeline-precision-ag/Model_Management/ZAF/runpsp.sh $(pwd)/vsr/tmp)";
        fi
      - |
      - if [ "$REGION" = "ARG" ]; then
          echo "B.....";
        fi
