version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  build:
    commands:
      - curl -LJ0 https://github.com/nayakashutosh09/awssetup/variables.sh
     # - echo ls $(pwd)/variables.sh
      - chmod +x $(pwd)/variables.sh
      - sh $(pwd)/variables.sh
     # - export REGION="ZAF"
      - echo "REGION is" $REGION
      - if [ "$REGION" == $REGION ]; then
          echo "A.....";
        elif [ "REGION" == $REGION ]; then
          echo "B.....";
        else
          echo "hey how are you";
        fi
