version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  build:
    commands:
      - curl -LJ0 https://github.com/nayakashutosh09/awssetup/variables.sh
      - echo ls $(pwd)/variables.sh
      - sh $(pwd)/variables.sh
      - if [ "$REGION" == "ZAF" ]; then
          echo "A....."
        elif [ "REGION" == "ARG" ]; then
          echo "B....."
        else
          echo "hey how are you"
        fi
