version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  build:
    commands:
      - docker build --build-arg REGION=ZAF -t dev . 
      - REGION=$(docker inspect --format ='{{index .Config.Labels "REGION"}}' dev)
      - echo "REGION is $REGION"
      - |
        if ["REGION" == "ZAF"]; then
          echo Logging in to Amazon ECR...
          aws --version
          echo $AWS_DEFAULT_REGION
          REPOSITORY_URI1=374898892977.dkr.ecr.us-east-1.amazonaws.com/vsr-h2o-model
          REPOSITORY_URI2=374898892977.dkr.ecr.us-east-1.amazonaws.com/vsr-pipeline
          aws sts get-caller-identity
          echo Logging in to Amazon ECR...
          curl -LJ0 https://github.com/nayakashutosh09/awssetup/pipeline-config.json
          aws s3 cp pipeline-config.json s3://ci-cd-pipeline-precision-ag/Model_Management/ZAF/
          echo $(pwd)
          mkdir -p $(pwd)/vsr/tmp
          echo ls $(pwd)/vsr/tmp
          aws s3 cp s3://ci-cd-pipeline-precision-ag/Model_Management/Mod_5.0_QC5 $(pwd)/vsr/tmp
          aws s3 cp s3://ci-cd-pipeline-precision-ag/Model_Management/ZAF/calibrateddata.csv $(pwd)/vsr/tmp
          aws s3 cp s3://ci-cd-pipeline-precision-ag/Model_Management/ZAF/regionaldata.json $(pwd)/vsr/tmp
          aws s3 cp s3://ci-cd-pipeline-precision-ag/Model_Management/ZAF/runh2o.sh $(pwd)/vsr/tmp
          aws s3 cp s3://ci-cd-pipeline-precision-ag/Model_Management/ZAF/runpsp.sh $(pwd)/vsr/tmp
          aws s3 cp s3://ci-cd-pipeline-precision-ag/Model_Management/ZAF/variables_file.sh $(pwd)/vsr/tmp
          aws s3 cp s3://ci-cd-pipeline-precision-ag/Model_Management/ZAF/yieldpotential.csv $(pwd)/vsr/tmp
          aws s3 cp s3://ci-cd-pipeline-precision-ag/Model_Management/ZAF/grid.csv $(pwd)/vsr/tmp
          aws s3 cp s3://ci-cd-pipeline-precision-ag/Model_Management/ZAF/rates.csv $(pwd)/vsr/tmp
          aws s3 cp s3://ci-cd-pipeline-precision-ag/Model_Management/ZAF/pipeline-config.json $(pwd)/vsr/tmp
          aws s3 cp s3://ci-cd-pipeline-precision-ag/Model_Management/ZAF/prescription.xml $(pwd)/vsr/tmp
          aws s3 cp s3://ci-cd-pipeline-precision-ag/Model_Management/ZAF/prescription.xsd $(pwd)/vsr/tmp
          echo $(pwd)/vsr/tmp
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 374898892977.dkr.ecr.us-east-1.amazonaws.com
        elif ["REGION" == "MEX"]; then
          echo "Ashu"
        elif ["REGION" == "ARG"]; then
          echo "xyz"
        else
          echo "xyzz"
        fi
