version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 374898892977.dkr.ecr.us-east-1.amazonaws.com
      - H2O_URI=374898892977.dkr.ecr.us-east-1.amazonaws.com/isr-table-generation
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - STAGE=${STAGE:=dev}
      - echo tag is $IMAGE_TAG
      - echo stage is $STAGE
      - echo Testing access
      - echo Grabbing the current latest versions to reuse layers if possible
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Pipeline Docker image...
      - echo Building the H2O Docker image...
#      - docker build -f Dockerfile-h2o --build-arg stage="dev" -t 374898892977.dkr.ecr.us-east-1.amazonaws.com/isr-table-generation:dev .
#      - docker build -f Dockerfile-h2o --build-arg stage="nonprod" -t 374898892977.dkr.ecr.us-east-1.amazonaws.com/isr-table-generation:nonprod .
      - >
        docker build -f Dockerfile-h2o
        --build-arg AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
        --build-arg AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
        --build-arg stage="dev"
        -t $H2O_URI:dev .
      - >
        docker build -f Dockerfile-h2o
        --build-arg AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
        --build-arg AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
        --build-arg stage="nonprod"
        -t $H2O_URI:nonprod .
      - docker tag $H2O_URI:dev $H2O_URI:dev
      - docker tag $H2O_URI:nonprod $H2O_URI:nonprod
      - echo Pushing the H2O Docker images...
      - docker push $H2O_URI:dev
      - docker push $H2O_URI:nonprod

  post_build:
    commands:
      - echo Build completed on `date`
