version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  build:
    commands:
      - curl -LJ0 https://github.com/nayakashutosh09/awssetup/variables.txt
      - echo $(pwd)
      - |
        while IFS= read -r line || [ -n "$line" ]; do
          export "$line"
        done < $(pwd)/variables.txt
      - echo "REGION is" $REGION
      - |
      - if [[ "$REGION" == "ZAF" ]]; then
          echo "A.....";
        elif [[ "$REGION" == "ARG" ]]; then
          echo "B.....";
        else
          echo "hey how are you";
        fi
