version: 2.1
jobs:
  test:
    machine:
      image: public.ecr.aws/lts/ubuntu:20.04
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run:
          command:
	    - aws --version
	    - echo $AWS_DEFAULT_REGION
	    - IMAGE_TAG=${COMMIT_HASH:=latest}
	    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 374898892977.dkr.ecr.us-east-1.amazonaws.com
            - REPOSITORY_URI=374898892977.dkr.ecr.us-east-1.amazonaws.com/isr-table-generation
	    - docker pull $REPOSITORY_URI:$IMAGE_TAG
            - sudo apt-get update
            - sudo apt install python3-pip
            - sudo pip3 install awsebcli --upgrade
      - run: cd ./app && npm run test
      - persist_to_workspace:
          root: .
          paths:
            - .
