version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
   build:
     commands:
       - echo Logging in to Amazon ECR...
       - aws --version
       - echo $AWS_DEFAULT_REGION
       - REPOSITORY_URI1=559866444233.dkr.ecr.us-east-1.amazonaws.com/vsr-h2o-model
       - REPOSITORY_URI2=374898892977.dkr.ecr.us-east-1.amazonaws.com/vsr-pipeline
       - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 559866444233.dkr.ecr.us-east-1.amazonaws.com
       - docker pull $REPOSITORY_URI1:prod
       - wget https://dsso-ss-analytics.s3.amazonaws.com/models/Mod_5.0_QC5
#       - echo $(pwd)
#       - docker run -it --rm -v$(pwd):$(pwd) $REPOSITORY_URI1:prod /bin/bash $(pwd)/runh2o.sh
#       - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 374898892977.dkr.ecr.us-east-1.amazonaws.com
#       - docker pull $REPOSITORY_URI2:prod
#       - docker run -it --rm -v$(pwd):$(pwd) $REPOSITORY_URI2:prod /bin/bash $(pwd)/runpsp.sh
#       - sh scripts/installer1.sh
artifacts:
  files:
    - '**/*'
