FROM public.ecr.aws/lts/ubuntu:20.04

WORKDIR /app
COPY . .

ENV DEBIAN_FRONTEND=noninteractive

RUN export LANGUAGE="en_US.UTF-8" && \
    ln -s /usr/share/zoneinfo/UTC /etc/localtime && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get update && \
    apt-get install -y nodejs npm && \
    apt-get install -y software-properties-common


RUN npm init -y && \
    npm install express 

RUN apt-get -qq update -y \
 && apt-get -qq upgrade -y \
 && apt-get -qq --fix-missing install -y \
            curl \
            ess \
            gdal-bin \
            git \
            jq \
            libgdal-dev \
            libproj-dev \
            libgeos-dev \
            libudunits2-dev \
            libv8-dev \
            libcairo2-dev \
            libnetcdf-dev \
            libspatialindex-dev \
            littler \
            python3 \
            python3-pip \
            python3-gdal \
            python3-boto3 \
            python3-pandas \
            r-base-core \
            r-base-dev \
 && pip3 install --upgrade pip \
 && apt-get autoclean && apt-get clean \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


RUN R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/gtable/gtable_0.3.0.tar.gz")' && \
    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/rlang/rlang_0.4.12.tar.gz")' && \
    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/glue/glue_1.6.0.tar.gz")' && \
    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/cli/cli_3.1.0.tar.gz")' && \
    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/lifecycle/lifecycle_1.0.1.tar.gz")' && \
    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/fansi/fansi_1.0.0.tar.gz")' && \
    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/utf8/utf8_1.2.2.tar.gz")' && \
    R -e 'install.packages("https://cran.r-project.org/src/contrib/ellipsis_0.3.2.tar.gz")' && \
    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/vctrs/vctrs_0.3.8.tar.gz")' && \
    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/crayon/crayon_1.4.2.tar.gz")' && \
    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/pillar/pillar_1.6.4.tar.gz")' && \
    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/farver/farver_2.1.0.tar.gz")' && \
    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/labeling/labeling_0.4.2.tar.gz")' && \
    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/colorspace/colorspace_2.0-2.tar.gz")' && \
    R -e 'install.packages("https://cran.r-project.org/src/contrib/munsell_0.5.0.tar.gz")' && \
    R -e 'install.packages("https://cran.r-project.org/src/contrib/R6_2.5.1.tar.gz")' && \
    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/RColorBrewer/RColorBrewer_1.1-2.tar.gz")'

#RUN R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/gtable/gtable_0.3.0.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/rlang/rlang_0.4.12.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/glue/glue_1.6.0.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/cli/cli_3.1.0.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/lifecycle/lifecycle_1.0.1.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/fansi/fansi_1.0.0.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/utf8/utf8_1.2.2.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/ellipsis_0.3.2.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/vctrs/vctrs_0.3.8.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/crayon/crayon_1.4.2.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/pillar/pillar_1.6.4.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/farver/farver_2.1.0.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/labeling/labeling_0.4.2.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/colorspace/colorspace_2.0-2.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/munsell_0.5.0.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/R6_2.5.1.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/RColorBrewer/RColorBrewer_1.1-2.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/viridisLite/viridisLite_0.4.0.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/scales/scales_1.1.1.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/magrittr/magrittr_2.0.1.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/pkgconfig_2.0.3.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/tibble/tibble_3.1.6.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/isoband/isoband_0.2.5.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/scales/scales_1.1.1.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/withr/withr_2.4.3.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/digest/digest_0.6.29.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/ggplot2/ggplot2_3.3.5.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/png/png_0.1-7.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/jpeg/jpeg_0.1-9.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/latticeExtra/latticeExtra_0.6-29.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/acepack/acepack_1.4.1.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/gridExtra_2.3.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/stringi/stringi_1.7.6.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/stringr/stringr_1.4.0.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/base64enc_0.1-3.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/fastmap/fastmap_1.1.0.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/ellipsis_0.3.2.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/htmltools/htmltools_0.5.2.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/jsonlite/jsonlite_1.7.2.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/yaml/yaml_2.2.1.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/htmlwidgets/htmlwidgets_1.5.4.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/evaluate/evaluate_0.14.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/xfun/xfun_0.29.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/highr/highr_0.9.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/knitr/knitr_1.37.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/backports_1.4.1.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/checkmate/checkmate_2.0.0.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/rstudioapi/rstudioapi_0.13.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/htmlTable/htmlTable_2.4.0.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/viridis/viridis_0.6.2.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/Formula/Formula_1.2-4.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/data.table/data.table_1.14.2.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/survival/survival_3.2-13.tar.gz")' && \
#    R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/Hmisc/Hmisc_4.6-0.tar.gz")'


COPY requirements.txt /requirements.txt
RUN pip3 install -r requirements.txt \
 && rm -f requirements.txt

RUN mkdir -p /vsr/tmp
COPY pipeline-config.json season-config.json ec-config.json scoring-config.json /vsr/tmp/
COPY R ApiIntegration.py run-engine.py /vsr/pipeline/

ARG stage=dev
ENV STAGE=${stage}

CMD ["node", "index.js"]
EXPOSE 3000
